<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <parent>
    <groupId>com.google.cloud.teleport.v2</groupId>
    <artifactId>dynamic-templates</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <modelVersion>4.0.0</modelVersion>
  <artifactId>aerospike-backup-to-bigtable</artifactId>

  <properties>
    <aerospike-backup-loader.version>1.0.0-SNAPSHOT</aerospike-backup-loader.version>
    <moshi.version>1.15.2</moshi.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>com.squareup.moshi</groupId>
      <artifactId>moshi</artifactId>
      <version>${moshi.version}</version>
    </dependency>
    <dependency>
      <groupId>com.google.cloud.teleport</groupId>
      <artifactId>it-google-cloud-platform</artifactId>
      <version>${project.version}</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.google.cloud.teleport.v2</groupId>
      <artifactId>bigtable-common</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.google.cloud.aerospike</groupId>
      <artifactId>backup-loader</artifactId>
      <version>${aerospike-backup-loader.version}</version>
    </dependency>
    <dependency>
      <groupId>com.google.truth</groupId>
      <artifactId>truth</artifactId>
      <version>${truth.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${surefire.version}</version>
        <configuration>
          <systemPropertyVariables combine.children="append">
            <!-- TODO: replace with a Google-managed URL. -->
            <sdkContainerImage>TODO:${beam.version}</sdkContainerImage>
          </systemPropertyVariables>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>