name: Aerospike Bigtable Migration Tools CI

on:
  push:
    branches:
      - main
    paths:
      - "aerospike-bigtable-migration-tools/**"
  pull_request:
    paths:
      - "aerospike-bigtable-migration-tools/**"

jobs:
  ci:
    name: Check the Aerospike Bigtable Migration Tools code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: C formatter
        working-directory: aerospike-bigtable-migration-tools
        run: |
          shopt -s globstar
          clang-format --dry-run --Werror -style=file -assume-filename=.clang-format **/*.c
      - name: Java formatter
        working-directory: aerospike-bigtable-migration-tools
        run: mvn -B -ntp spotless:check
      # TODO: test other submodules
      - name: Java unit tests
        working-directory: aerospike-bigtable-migration-tools
        run: mvn -B -ntp test -pl adapter,replicator
      # TODO: Download the sink .jar from maven once Google starts publishing it.
      - name: Create integration_test_plugins dir and necessary subdirectories
        working-directory: aerospike-bigtable-migration-tools
        run: mkdir -p replicator/integration_test_plugins/sink
      - name: Download sink .jar
        working-directory: aerospike-bigtable-migration-tools
        run: mvn -s .github/aerospike-migration-tools-m2.settings.xml -B -ntp dependency:copy -Dartifact=com.google.cloud.kafka.connect.bigtable:sink:1.0.0-SNAPSHOT:jar:jar-with-dependencies -DoutputDirectory=replicator/integration_test_plugins/sink
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Show integration_test_plugins dir contents
        working-directory: aerospike-bigtable-migration-tools
        run: tree --du replicator/integration_test_plugins
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: latest
          install_components: beta,bigtable
      - name: Integration tests
        working-directory: aerospike-bigtable-migration-tools
        run: |
          set -euo pipefail
          gcloud beta emulators bigtable start --host-port=0.0.0.0:8086 &
          mvn -B -ntp verify -pl adapter,replicator -DskipUnitTests
